[31m[1mERROR   [0m root:conftest.py:98 Arquivo /Users/lpsp/Documents/automacao-api/casos_de_teste.csv n√£o encontrado!